//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WispStudios.Docker.ContainerPatcher.Core.Resources.es {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WispStudios.Docker.ContainerPatcher.Core.Resources.es.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Contenedor &apos;{0}&apos; no encontrado..
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_ContainerNotFoundError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_ContainerNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de API de Docker: {0} (Código de estado: {1}).
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_DockerApiException {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_DockerApiException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inesperado al conectar con Docker: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_GeneralException {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El host &apos;{0}&apos; no es un URI válido.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_HostIsNotValidURIError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_HostIsNotValidURIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló al conectar con Docker en {0}: {1}.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_HttpRequestException {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_HttpRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Se debe especificar --replace-tag o --restore-tag..
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_ReplaceTagOrRestoreTagUnspecifiedError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_ReplaceTagOrRestoreTagUnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia: Ruta no encontrada: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_ParseInputPaths_WarningPathNotFound {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ParseInputPaths_WarningPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: --input y --output son obligatorios en el modo de reemplazo.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_InputOutputRequiredError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_InputOutputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se encontraron rutas de entrada válidas..
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_NoValidInputPathsFoundError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_NoValidInputPathsFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Imagen de respaldo {0}:{1} no encontrada..
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_BackupImageNotFoundError {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_BackupImageNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al menos una ruta de entrada debe proporcionarse para el perfil &apos;{0}&apos;..
        /// </summary>
        internal static string InputNullOrEmpty {
            get {
                return ResourceManager.GetString("InputNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta de salida debe proporcionarse para el perfil &apos;{0}&apos;..
        /// </summary>
        internal static string OutputNullOrEmpty {
            get {
                return ResourceManager.GetString("OutputNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los perfiles de carga son nulos, algo salió mal..
        /// </summary>
        internal static string ProfileManager_ParseLoadProfilesAsync_LoadProfilesWasNullError {
            get {
                return ResourceManager.GetString("ProfileManager_ParseLoadProfilesAsync_LoadProfilesWasNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El directorio de perfiles &apos;{0}&apos; no se encontró o fue eliminado durante la operación..
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_DirectoryNotFoundError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_DirectoryNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Falló al listar perfiles. {0}.
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_GeneralError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Problema al acceder al directorio de perfiles. {0}.
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_IOException {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron perfiles..
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_NoProfilesFoundError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_NoProfilesFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La ruta del directorio de perfiles es demasiado larga para tu sistema operativo..
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_PathTooLongError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El directorio de perfiles no se pudo inicializar y la ejecución no puede continuar..
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_ProfileDirectoryIsNullError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_ProfileDirectoryIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No tienes permiso para acceder al directorio de perfiles. Intenta ejecutar como administrador..
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_UnauthorizedAccessExceptionError {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_UnauthorizedAccessExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No tienes permiso para leer el archivo de perfil. Intenta ejecutar como administrador..
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_Error_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_Error_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El archivo de perfil &apos;{0}.json&apos; fue eliminado entre la verificación y la carga..
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_FileNotFoundException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Falló al cargar el perfil &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_GeneralException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se puede leer el archivo de perfil. El archivo puede estar en uso por otro proceso. {0}.
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_IOException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El archivo de perfil contiene JSON inválido. {0}.
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_JsonException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_JsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Falló al deserializar los datos del perfil. El formato del perfil puede ser incompatible. {0}.
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_JsonSerializationException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_JsonSerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil &apos;{0}&apos; es nulo, la ejecución no continuará en este perfil..
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_NullReferenceException {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil &apos;{0}&apos; no existe..
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_ProfileDoesNotExistError {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_ProfileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Falló al serializar los datos del perfil. {0}.
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_FailedToSerializeProfileError {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_FailedToSerializeProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Falló al guardar el perfil &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_GeneralException {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Nombre de perfil inválido. Los nombres de perfil no pueden contener caracteres inválidos. {0}.
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_InvalidProfileNameError {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_InvalidProfileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se puede escribir el archivo de perfil. El archivo puede estar en uso por otro proceso. {0}.
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_IOException {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El nombre o la ruta del perfil es demasiado largo para tu sistema operativo..
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_PathTooLongError {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del perfil no puede ser analizado correctamente..
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_ProfileNameCannotBeParsed1 {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_ProfileNameCannotBeParsed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del perfil debe ser un nombre de archivo válido, no puede incluir espacios o puntos, y debe contener al menos un carácter alfanumérico, guiones bajos o guiones.
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_ProfileNameCannotBeParsed2 {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_ProfileNameCannotBeParsed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El perfil de guardado es nulo, algo salió mal..
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_ProfileWasNullError {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_ProfileWasNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No tienes permiso para guardar el perfil. Intenta ejecutar como administrador..
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El directorio &apos;{0}&apos; no existe. Por favor, créelo primero..
        /// </summary>
        internal static string ProfileManager_TryInitializeProfileDirectoryPath_DirectoryNotFoundError {
            get {
                return ResourceManager.GetString("ProfileManager_TryInitializeProfileDirectoryPath_DirectoryNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Ocurrió un problema al intentar resolver el directorio de perfiles &apos;{0}&apos;.
        /// </summary>
        internal static string ProfileManager_TryInitializeProfileDirectoryPath_IOExceptionOccurred {
            get {
                return ResourceManager.GetString("ProfileManager_TryInitializeProfileDirectoryPath_IOExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La creación del directorio &apos;{0}&apos; no es compatible..
        /// </summary>
        internal static string ProfileManager_TryInitializeProfileDirectoryPath_NotSupportedError {
            get {
                return ResourceManager.GetString("ProfileManager_TryInitializeProfileDirectoryPath_NotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El nombre o la ruta del directorio de perfiles &apos;{0}&apos; es demasiado largo para tu sistema operativo..
        /// </summary>
        internal static string ProfileManager_TryInitializeProfileDirectoryPath_PathTooLongError {
            get {
                return ResourceManager.GetString("ProfileManager_TryInitializeProfileDirectoryPath_PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No tienes permiso para crear el directorio de perfiles &apos;{0}&apos;. Intenta ejecutar como administrador..
        /// </summary>
        internal static string ProfileManager_TryInitializeProfileDirectoryPath_UnauthorizedAccessError {
            get {
                return ResourceManager.GetString("ProfileManager_TryInitializeProfileDirectoryPath_UnauthorizedAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenedor de destino debe proporcionarse para el perfil &apos;{0}&apos;..
        /// </summary>
        internal static string TargetNullOrEmpty {
            get {
                return ResourceManager.GetString("TargetNullOrEmpty", resourceCulture);
            }
        }
    }
}
