//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WispStudios.Docker.ContainerPatcher.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WispStudios.Docker.ContainerPatcher.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to tar: {0} -&gt; {1}.
        /// </summary>
        public static string ContainerPatchAgent_CopyFilesToContainer_AddedToTarMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_AddedToTarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} files to container at path: {1}.
        /// </summary>
        public static string ContainerPatchAgent_CopyFilesToContainer_CopyingFilesToContainerAtPathMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_CopyingFilesToContainerAtPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files copied successfully.
        /// </summary>
        public static string ContainerPatchAgent_CopyFilesToContainer_FilesCopiedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_FilesCopiedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary tar file deleted.
        /// </summary>
        public static string ContainerPatchAgent_CopyFilesToContainer_TemporaryTarFileDeletedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_TemporaryTarFileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files successfully copied to container in copy-only mode..
        /// </summary>
        public static string ContainerPatchAgent_CopyOnlyMode_FilesCopiedToContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyOnlyMode_FilesCopiedToContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed {0} input path(s) for copy-only operation..
        /// </summary>
        public static string ContainerPatchAgent_CopyOnlyMode_ParsedInputPathsMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyOnlyMode_ParsedInputPathsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Docker. Target container: {0}.
        /// </summary>
        public static string ContainerPatchAgent_ExecuteAsync_ConnectedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image: {0}.
        /// </summary>
        public static string ContainerPatchAgent_ExecuteAsync_CurrentImageMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_CurrentImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found container: {0} ({1}).
        /// </summary>
        public static string ContainerPatchAgent_ExecuteAsync_FoundContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_FoundContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string ContainerPatchAgent_ExecuteAsync_OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup image created.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_BackupCreatedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_BackupCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing changes to {0}:{1}.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_CommittingChangesMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_CommittingChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container changes committed to {0}:{1}.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_ContainerChangesCommittedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerChangesCommittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container restarted.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_ContainerRestartedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerRestartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container stopped.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_ContainerStoppedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup image {0}:{1}.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_CreatingBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_CreatingBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed {0} input paths.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_ParsedInputPathsMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ParsedInputPathsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting container....
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_RestartingContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_RestartingContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in REPLACE mode with backup tag: {0}.
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_RunningReplaceModeMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_RunningReplaceModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping container....
        /// </summary>
        public static string ContainerPatchAgent_ReplaceMode_StoppingContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_StoppingContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container started.
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_ContainerStartedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_ContainerStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container successfully restored from backup.
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_ContainerSuccessfullyRestoredFromBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_ContainerSuccessfullyRestoredFromBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new container from backup image {0}:{1}.
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_CreatingNewContainerFromBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_CreatingNewContainerFromBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New container created: {0}.
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_NewContainerCreatedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_NewContainerCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing current container....
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_RemovingCurrentContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_RemovingCurrentContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in RESTORE mode with tag: {0}.
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_RunningInRestoreModeMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_RunningInRestoreModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting restored container....
        /// </summary>
        public static string ContainerPatchAgent_RestoreMode_StartingRestoredContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_StartingRestoredContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and modify a container..
        /// </summary>
        public static string Example1Help {
            get {
                return ResourceManager.GetString("Example1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a container from backup..
        /// </summary>
        public static string Example2Help {
            get {
                return ResourceManager.GetString("Example2Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal scenario.
        /// </summary>
        public static string ExamplesNormalScenario {
            get {
                return ResourceManager.GetString("ExamplesNormalScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read more lines.
        /// </summary>
        public static string ExamplesReadMoreLines {
            get {
                return ResourceManager.GetString("ExamplesReadMoreLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specify bytes.
        /// </summary>
        public static string ExamplesSpecifyBytes {
            get {
                return ResourceManager.GetString("ExamplesSpecifyBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suppress summary.
        /// </summary>
        public static string ExamplesSuppressSummary {
            get {
                return ResourceManager.GetString("ExamplesSuppressSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from bottom:.
        /// </summary>
        public static string FromBottom {
            get {
                return ResourceManager.GetString("FromBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from top:.
        /// </summary>
        public static string FromTop {
            get {
                return ResourceManager.GetString("FromTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes to be printed from the beginning or end of the file..
        /// </summary>
        public static string HelpTextBytes {
            get {
                return ResourceManager.GetString("HelpTextBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file to be processed..
        /// </summary>
        public static string HelpTextFileName {
            get {
                return ResourceManager.GetString("HelpTextFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines to be printed from the beginning or end of the file..
        /// </summary>
        public static string HelpTextLines {
            get {
                return ResourceManager.GetString("HelpTextLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses summary messages..
        /// </summary>
        public static string HelpTextQuiet {
            get {
                return ResourceManager.GetString("HelpTextQuiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays first lines of a file..
        /// </summary>
        public static string HelpTextVerbHead {
            get {
                return ResourceManager.GetString("HelpTextVerbHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays last lines of a file..
        /// </summary>
        public static string HelpTextVerbTail {
            get {
                return ResourceManager.GetString("HelpTextVerbTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target host address..
        /// </summary>
        public static string HostHelp {
            get {
                return ResourceManager.GetString("HostHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV list of files or directories to transfer..
        /// </summary>
        public static string InputHelp {
            get {
                return ResourceManager.GetString("InputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the language of the application. (es, fr).
        /// </summary>
        public static string LanguageHelp {
            get {
                return ResourceManager.GetString("LanguageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List profiles that currently exist..
        /// </summary>
        public static string ListProfilesHelp {
            get {
                return ResourceManager.GetString("ListProfilesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a comma separated list of existing profiles and executes them in order..
        /// </summary>
        public static string LoadProfilesHelp {
            get {
                return ResourceManager.GetString("LoadProfilesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogType_Error {
            get {
                return ResourceManager.GetString("LogType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LogType_Fatal {
            get {
                return ResourceManager.GetString("LogType_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LogType_Info {
            get {
                return ResourceManager.GetString("LogType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        public static string LogType_Warn {
            get {
                return ResourceManager.GetString("LogType_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        public static string OptionsGroupWord {
            get {
                return ResourceManager.GetString("OptionsGroupWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path inside the target container..
        /// </summary>
        public static string OutputHelp {
            get {
                return ResourceManager.GetString("OutputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Profiles:.
        /// </summary>
        public static string ProfileManager_PrintProfilesList_CurrentProfilesMessage {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_CurrentProfilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing profile &apos;{0}&apos;..
        /// </summary>
        public static string ProfileManager_ResolveProfileAsync_ExecutingProfileMessage {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_ExecutingProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved profile &apos;{0}&apos; successfully..
        /// </summary>
        public static string ProfileManager_SaveProfileAsync_SavedProfileMessage {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_SavedProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading .
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup tag to save the original container state..
        /// </summary>
        public static string ReplaceTagHelp {
            get {
                return ResourceManager.GetString("ReplaceTagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag to restore (reverting to the backup version)..
        /// </summary>
        public static string RestoreTagHelp {
            get {
                return ResourceManager.GetString("RestoreTagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the parameters passed as a profile for future execution..
        /// </summary>
        public static string SaveProfileHelp {
            get {
                return ResourceManager.GetString("SaveProfileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnost &apos;{0}&apos; je definována ve špatném formátu..
        /// </summary>
        public static string SentenceBadFormatConversionErrorOption {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value not bound to option name is defined with a bad format..
        /// </summary>
        public static string SentenceBadFormatConversionErrorValue {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadFormatTokenError {
            get {
                return ResourceManager.GetString("SentenceBadFormatTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceBadVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR(S):.
        /// </summary>
        public static string SentenceErrorsHeadingText {
            get {
                return ResourceManager.GetString("SentenceErrorsHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        public static string SentenceHelpCommandTextOption {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more information on a specific command..
        /// </summary>
        public static string SentenceHelpCommandTextVerb {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required option &apos;{0}&apos; is missing..
        /// </summary>
        public static string SentenceMissingRequiredOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value not bound to option name is missing..
        /// </summary>
        public static string SentenceMissingRequiredValueError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has no value..
        /// </summary>
        public static string SentenceMissingValueOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingValueOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: {0} are not compatible with {1}..
        /// </summary>
        public static string SentenceMutuallyExclusiveSetErrors {
            get {
                return ResourceManager.GetString("SentenceMutuallyExclusiveSetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb selected..
        /// </summary>
        public static string SentenceNoVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceNoVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined multiple times..
        /// </summary>
        public static string SentenceRepeatedOptionError {
            get {
                return ResourceManager.GetString("SentenceRepeatedOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string SentenceRequiredWord {
            get {
                return ResourceManager.GetString("SentenceRequiredWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence option &apos;{0}&apos; is defined with fewer or more items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorOption {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence value not bound to option name is defined with fewer items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorValue {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value to option &apos;{0}&apos;: {1}.
        /// </summary>
        public static string SentenceSetValueExceptionError {
            get {
                return ResourceManager.GetString("SentenceSetValueExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is unknown..
        /// </summary>
        public static string SentenceUnknownOptionError {
            get {
                return ResourceManager.GetString("SentenceUnknownOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE:.
        /// </summary>
        public static string SentenceUsageHeadingText {
            get {
                return ResourceManager.GetString("SentenceUsageHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        public static string SentenceVersionCommandText {
            get {
                return ResourceManager.GetString("SentenceVersionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target container name or identifier..
        /// </summary>
        public static string TargetHelp {
            get {
                return ResourceManager.GetString("TargetHelp", resourceCulture);
            }
        }
    }
}
