//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WispStudios.Docker.ContainerPatcher.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WispStudios.Docker.ContainerPatcher.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to tar: {0} -&gt; {1}.
        /// </summary>
        internal static string ContainerPatchAgent_CopyFilesToContainer_AddedToTarMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_AddedToTarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} files to container at path: {1}.
        /// </summary>
        internal static string ContainerPatchAgent_CopyFilesToContainer_CopyingFilesToContainerAtPathMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_CopyingFilesToContainerAtPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files copied successfully.
        /// </summary>
        internal static string ContainerPatchAgent_CopyFilesToContainer_FilesCopiedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_FilesCopiedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary tar file deleted.
        /// </summary>
        internal static string ContainerPatchAgent_CopyFilesToContainer_TemporaryTarFileDeletedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_CopyFilesToContainer_TemporaryTarFileDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Docker. Target container: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_ConnectedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_CurrentImageMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_CurrentImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found container: {0} ({1}).
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_FoundContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_FoundContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        internal static string ContainerPatchAgent_ExecuteAsync_OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ExecuteAsync_OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup image created.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_BackupCreatedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_BackupCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing changes to {0}:{1}.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_CommittingChangesMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_CommittingChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container changes committed to {0}:{1}.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_ContainerChangesCommittedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerChangesCommittedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container restarted.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_ContainerRestartedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerRestartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container stopped.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_ContainerStoppedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ContainerStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup image {0}:{1}.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_CreatingBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_CreatingBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed {0} input paths.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_ParsedInputPathsMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_ParsedInputPathsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting container....
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_RestartingContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_RestartingContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in REPLACE mode with backup tag: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_RunningReplaceModeMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_RunningReplaceModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping container....
        /// </summary>
        internal static string ContainerPatchAgent_ReplaceMode_StoppingContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_ReplaceMode_StoppingContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container started.
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_ContainerStartedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_ContainerStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container successfully restored from backup.
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_ContainerSuccessfullyRestoredFromBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_ContainerSuccessfullyRestoredFromBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new container from backup image {0}:{1}.
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_CreatingNewContainerFromBackupMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_CreatingNewContainerFromBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New container created: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_NewContainerCreatedMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_NewContainerCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing current container....
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_RemovingCurrentContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_RemovingCurrentContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in RESTORE mode with tag: {0}.
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_RunningInRestoreModeMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_RunningInRestoreModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting restored container....
        /// </summary>
        internal static string ContainerPatchAgent_RestoreMode_StartingRestoredContainerMessage {
            get {
                return ResourceManager.GetString("ContainerPatchAgent_RestoreMode_StartingRestoredContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and modify a container..
        /// </summary>
        internal static string Example1Help {
            get {
                return ResourceManager.GetString("Example1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore a container from backup..
        /// </summary>
        internal static string Example2Help {
            get {
                return ResourceManager.GetString("Example2Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target host address..
        /// </summary>
        internal static string HostHelp {
            get {
                return ResourceManager.GetString("HostHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV list of files or directories to transfer..
        /// </summary>
        internal static string InputHelp {
            get {
                return ResourceManager.GetString("InputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the language of the application..
        /// </summary>
        internal static string LanguageHelp {
            get {
                return ResourceManager.GetString("LanguageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List profiles that currently exist..
        /// </summary>
        internal static string ListProfilesHelp {
            get {
                return ResourceManager.GetString("ListProfilesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a comma separated list of existing profiles and executes them in order..
        /// </summary>
        internal static string LoadProfilesHelp {
            get {
                return ResourceManager.GetString("LoadProfilesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LogType_Error {
            get {
                return ResourceManager.GetString("LogType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string LogType_Fatal {
            get {
                return ResourceManager.GetString("LogType_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LogType_Info {
            get {
                return ResourceManager.GetString("LogType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn.
        /// </summary>
        internal static string LogType_Warn {
            get {
                return ResourceManager.GetString("LogType_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path inside the target container..
        /// </summary>
        internal static string OutputHelp {
            get {
                return ResourceManager.GetString("OutputHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Profiles:.
        /// </summary>
        internal static string ProfileManager_PrintProfilesList_CurrentProfilesMessage {
            get {
                return ResourceManager.GetString("ProfileManager_PrintProfilesList_CurrentProfilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing profile &apos;{0}&apos;..
        /// </summary>
        internal static string ProfileManager_ResolveProfileAsync_ExecutingProfileMessage {
            get {
                return ResourceManager.GetString("ProfileManager_ResolveProfileAsync_ExecutingProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved profile &apos;{0}&apos; successfully..
        /// </summary>
        internal static string ProfileManager_SaveProfileAsync_SavedProfileMessage {
            get {
                return ResourceManager.GetString("ProfileManager_SaveProfileAsync_SavedProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup tag to save the original container state..
        /// </summary>
        internal static string ReplaceTagHelp {
            get {
                return ResourceManager.GetString("ReplaceTagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag to restore (reverting to the backup version)..
        /// </summary>
        internal static string RestoreTagHelp {
            get {
                return ResourceManager.GetString("RestoreTagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the parameters passed as a profile for future execution..
        /// </summary>
        internal static string SaveProfileHelp {
            get {
                return ResourceManager.GetString("SaveProfileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target container name or identifier..
        /// </summary>
        internal static string TargetHelp {
            get {
                return ResourceManager.GetString("TargetHelp", resourceCulture);
            }
        }
    }
}
